/*
 *
 * HomePage constants
 *
 */
export const FETCH_STRING_REQUEST = 'FETCH_STRING_REQUEST';
export const FETCH_STRING_SUCCESS = 'FETCH_STRING_SUCCESS';
export const FETCH_STRING_FAILURE = 'FETCH_STRING_FAILURE';
